steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE_NAME}', '.']
- name: '${_IMAGE_NAME}'
images: ['${_IMAGE_NAME}']
substitutions:
    _IMAGE_NAME: gcr.io/mobilere/example-cloud-build-image
